import React from 'react';
import loading from '../../assets/img/loading.gif'
import './style.css'

const Home = () => {

    return (
        <div>
            <h2>EM CONSTRUÇÃO</h2>
            <br></br>
            
            <img src={loading} ></img>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget sit amet tellus cras adipiscing. Id neque aliquam vestibulum morbi blandit cursus risus. Vitae tortor condimentum lacinia quis. Lacus sed turpis tincidunt id aliquet risus feugiat in. Ultrices in iaculis nunc sed augue. Auctor urna nunc id cursus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Rhoncus aenean vel elit scelerisque. Auctor eu augue ut lectus. Rhoncus dolor purus non enim praesent elementum. Et egestas quis ipsum suspendisse. Duis ut diam quam nulla porttitor massa id neque aliquam. Aliquam id diam maecenas ultricies.

Amet justo donec enim diam vulputate ut pharetra sit amet. Et ligula ullamcorper malesuada proin libero nunc. Mauris sit amet massa vitae tortor condimentum lacinia. Lorem ipsum dolor sit amet. Sodales ut etiam sit amet nisl. Imperdiet proin fermentum leo vel orci porta. Quis enim lobortis scelerisque fermentum dui faucibus in. Sit amet cursus sit amet. Sit amet volutpat consequat mauris nunc congue nisi vitae. Quam viverra orci sagittis eu volutpat. Tincidunt praesent semper feugiat nibh sed pulvinar. Eu mi bibendum neque egestas congue quisque egestas diam in. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Duis at tellus at urna condimentum. Pellentesque diam volutpat commodo sed egestas egestas. Risus nullam eget felis eget nunc.

Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Cum sociis natoque penatibus et. Scelerisque eu ultrices vitae auctor. Lacus luctus accumsan tortor posuere ac ut consequat semper. Ultrices in iaculis nunc sed augue. Mi quis hendrerit dolor magna. Dui id ornare arcu odio ut sem nulla. Vitae et leo duis ut diam quam nulla. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Eu lobortis elementum nibh tellus molestie nunc. Viverra maecenas accumsan lacus vel. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Tellus mauris a diam maecenas sed enim ut sem. Scelerisque mauris pellentesque pulvinar pellentesque habitant. Hac habitasse platea dictumst quisque sagittis purus. Ac tortor vitae purus faucibus ornare. Lacus sed turpis tincidunt id aliquet risus feugiat. Enim nulla aliquet porttitor lacus.

Eu turpis egestas pretium aenean pharetra magna ac. Ut tellus elementum sagittis vitae et leo duis ut. Id semper risus in hendrerit. Nunc lobortis mattis aliquam faucibus. Vel eros donec ac odio. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Duis convallis convallis tellus id interdum velit laoreet id. Adipiscing elit duis tristique sollicitudin nibh. Tincidunt vitae semper quis lectus. Porta lorem mollis aliquam ut porttitor. Nisl vel pretium lectus quam id. Ut sem nulla pharetra diam sit amet nisl suscipit. Libero enim sed faucibus turpis in eu mi bibendum. In massa tempor nec feugiat nisl pretium fusce. Magna eget est lorem ipsum dolor sit amet. Posuere ac ut consequat semper viverra. Suspendisse potenti nullam ac tortor. Pellentesque nec nam aliquam sem et tortor consequat id.

Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Proin libero nunc consequat interdum varius. Dictum varius duis at consectetur lorem donec massa sapien. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Id diam maecenas ultricies mi eget mauris pharetra. Praesent tristique magna sit amet purus gravida quis blandit turpis. Mattis aliquam faucibus purus in massa tempor. Nulla at volutpat diam ut venenatis. Accumsan in nisl nisi scelerisque eu. Pulvinar elementum integer enim neque. Euismod lacinia at quis risus sed. Tortor posuere ac ut consequat semper viverra nam. Eros donec ac odio tempor orci dapibus.</p>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget sit amet tellus cras adipiscing. Id neque aliquam vestibulum morbi blandit cursus risus. Vitae tortor condimentum lacinia quis. Lacus sed turpis tincidunt id aliquet risus feugiat in. Ultrices in iaculis nunc sed augue. Auctor urna nunc id cursus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Rhoncus aenean vel elit scelerisque. Auctor eu augue ut lectus. Rhoncus dolor purus non enim praesent elementum. Et egestas quis ipsum suspendisse. Duis ut diam quam nulla porttitor massa id neque aliquam. Aliquam id diam maecenas ultricies.

Amet justo donec enim diam vulputate ut pharetra sit amet. Et ligula ullamcorper malesuada proin libero nunc. Mauris sit amet massa vitae tortor condimentum lacinia. Lorem ipsum dolor sit amet. Sodales ut etiam sit amet nisl. Imperdiet proin fermentum leo vel orci porta. Quis enim lobortis scelerisque fermentum dui faucibus in. Sit amet cursus sit amet. Sit amet volutpat consequat mauris nunc congue nisi vitae. Quam viverra orci sagittis eu volutpat. Tincidunt praesent semper feugiat nibh sed pulvinar. Eu mi bibendum neque egestas congue quisque egestas diam in. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Duis at tellus at urna condimentum. Pellentesque diam volutpat commodo sed egestas egestas. Risus nullam eget felis eget nunc.

Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Cum sociis natoque penatibus et. Scelerisque eu ultrices vitae auctor. Lacus luctus accumsan tortor posuere ac ut consequat semper. Ultrices in iaculis nunc sed augue. Mi quis hendrerit dolor magna. Dui id ornare arcu odio ut sem nulla. Vitae et leo duis ut diam quam nulla. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Eu lobortis elementum nibh tellus molestie nunc. Viverra maecenas accumsan lacus vel. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Tellus mauris a diam maecenas sed enim ut sem. Scelerisque mauris pellentesque pulvinar pellentesque habitant. Hac habitasse platea dictumst quisque sagittis purus. Ac tortor vitae purus faucibus ornare. Lacus sed turpis tincidunt id aliquet risus feugiat. Enim nulla aliquet porttitor lacus.

Eu turpis egestas pretium aenean pharetra magna ac. Ut tellus elementum sagittis vitae et leo duis ut. Id semper risus in hendrerit. Nunc lobortis mattis aliquam faucibus. Vel eros donec ac odio. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Duis convallis convallis tellus id interdum velit laoreet id. Adipiscing elit duis tristique sollicitudin nibh. Tincidunt vitae semper quis lectus. Porta lorem mollis aliquam ut porttitor. Nisl vel pretium lectus quam id. Ut sem nulla pharetra diam sit amet nisl suscipit. Libero enim sed faucibus turpis in eu mi bibendum. In massa tempor nec feugiat nisl pretium fusce. Magna eget est lorem ipsum dolor sit amet. Posuere ac ut consequat semper viverra. Suspendisse potenti nullam ac tortor. Pellentesque nec nam aliquam sem et tortor consequat id.

Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Proin libero nunc consequat interdum varius. Dictum varius duis at consectetur lorem donec massa sapien. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Id diam maecenas ultricies mi eget mauris pharetra. Praesent tristique magna sit amet purus gravida quis blandit turpis. Mattis aliquam faucibus purus in massa tempor. Nulla at volutpat diam ut venenatis. Accumsan in nisl nisi scelerisque eu. Pulvinar elementum integer enim neque. Euismod lacinia at quis risus sed. Tortor posuere ac ut consequat semper viverra nam. Eros donec ac odio tempor orci dapibus.</p>
        </div>
    );
}

export default Home;